blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blogapp.feeds import AllPostRss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('all/rss/', AllPostRss(), name='rss')
]

blogapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', views.detail, name='detail'),
    re_path('archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/', views.archives, name='archives'),
    path('category/<int:pk>/', views.category, name='category')
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

class Tag(models.Model):
    name = models.CharField(max_length=50)
	
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
	
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)
    content = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    viewnum = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.viewnum += 1
        self.save(update_fields=['viewnum'])
    
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.content))[:54]

        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
	
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['-created_time']

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from django.utils.html import strip_tags
import markdown

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blogapp/index.html', context={'post_list': post_list})

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blogapp/index.html', context={'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blogapp/index.html', context={'post_list': post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    post.content = markdown.markdown(strip_tags(post.content),
				extensions=[
					'markdown.extensions.extra',
					'markdown.extensions.codehilite',
        				'markdown.extensions.toc',
				], safe_mode=True)
    return render(request, 'blogapp/detail.html', context={'post': post})

templates/base.html
{% load blogtags %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.js"></script>
    </head>
    <body>
        <div class="ts stackable grid">
            <div class="three wide column"></div>
            <div class="ten wide column">
                <div class="ts stackable borderless flatted large menu">
                    <div class="header item">WoodMan</div>
                    <div class="right menu">
                        <a class="item" href="/">首頁</a>
                        <a class="item">關於</a>
                        <a class="item" href="{% url 'rss' %}">RSS</a>
                        <div class="ts borderless right icon input">
                            <input type="text" placeholder="搜尋">
                            <i class="search icon"></i>
                        </div>
                    </div>
                </div>
                <div class="ts stackable grid">
                    <div class="eleven wide column">
                        {% block content %}
                        {% endblock %}
                    </div>
                    <div class="one wide column"></div>
                    <div class="four wide column">
                        <h3 class="ts left aligned header">New Post</h3>
                        <div class="ts list">
                            {% get_recent_posts as recent_post_list %}
                            {% for post in recent_post_list %}
                                <a class="item" href="{{ post.get_absolute_url }}">
                                    <i class="angle right icon"></i>
                                    <div class="content">
                                        <div class="header">{{ post.title }}</div>
                                    </div>
                                </a>
                            {% empty %}
                                <p>目前沒貼文</p>
                            {% endfor %}
                        </div>
                        <h3 class="ts left aligned header">Date</h3>
                        <div class="ts list">
                            {% archives as date_list %}
                            {% for date in date_list %}
                                <a class="item" href="{% url 'blog:archives' date.year date.month%}">
                                    <i class="calendar icon"></i>
                                    <div class="content">
                                        <div class="header">{{ date.year }} 年 {{ date.month }} 月</div>
                                    </div>
                                </a>
                            {% empty %}
                                <p>目前沒貼文</p>
                            {% endfor %}
                        </div>
                        <h3 class="ts left aligned header">分類</h3>
                        <div class="ts list">
                            {% get_categories as category_list %}
                            {% for category in category_list %}
                                <a class="item" href="{% url 'blog:category' category.pk  %}">
                                    <i class="time icon"></i>
                                    <div class="content">
                                        <div class="header">{{ category.name }}</div>
                                    </div>
                                </a>
                            {% empty %}
                                <p>目前沒分類</p>
                            {% endfor %}
                        </div>
                        <h3 class="ts left aligned header">Tags</h3>
                        {% get_tags as tag_list %}
                        {% for tag in tag_list %}
                            <div class="ts circular horizontal label">{{ tag.name }}</div>
                        {% empty %}
                            <p>目前沒標籤</p>
                        {% endfor %}
                        </div>
                    </div>
                </div>				
            </div>
            <div class="three wide column"></div>
        </div>
    </body>
</html>

templates/blogapp/detail.html
{% extends "base.html" %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <h2 class="ts center aligned header">
        {{ post.title }}
    </h2>
    <div class="ts center aligned tiny header">{{ post.category.name }} ● {{ post.created_time }} ● {{ post.author }} ● {{ post.viewnum }} 人閱讀</div>
    <div class="ts basic segment">
        {{ post.content|safe }}
    </div>
{% endblock %}

templates/blogapp/index.html
{% extends "base.html" %}
{% block title %}Django Blog{% endblock %}
{% block content %}
    {% for post in post_list %}
        <h2 class="ts center aligned header">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <div class="ts very narrow container">
            {{ post.excerpt }}
        </div>
        <div class="ts center aligned tiny header">{{ post.category.name }} ● {{ post.created_time }} ● {{ post.viewnum }} 人閱讀</div>
        <div class="ts divider"></div>
    {% empty %}
        <div class="ts slate">
            <span class="header">目前還沒有文章QwQ</span>
        </div>
    {% endfor %}
{% endblock %}